name: Prova GitHub Actions
on: [push]
jobs:
  Prova-Github-Actions:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout del codi del repositori
        uses: actions/checkout@v6
        
      - name: Llistat de fitxers del repositori
        run: |
          ls -la
          
      - name: Modificat fitxer.txt
        run: |
          echo "Executat "`date` >> fitxer.txt
          echo "Mostrar contingut de fitxer.txt:\n"
          cat fitxer.txt
          
      - name: commit i push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add --all
          git commit -m "Afegit contingut a fitxer.txt"
          git push
